export const projects=[
 {title:'Global Sales & Profitability Analytics',category:'BUSINESS INTELLIGENCE',description:'Executive reporting across countries, organizations and business units with automated KPI tracking and interactive Power BI experiences.',tags:['Power BI','DAX','Dataflows','Databricks'],type:'sales'},
 {title:'Order Creation & API Monitoring',category:'OPERATIONAL ANALYTICS',description:'Operational analytics for monitoring complex order-processing workflows across APIs, cloud services and enterprise databases.',tags:['Power BI','Azure','KQL','SQL','Application Insights'],type:'monitor'},
 {title:'Cloud Data & Reporting Automation',category:'DATA ENGINEERING',description:'Automated ingestion and transformation pipelines connecting enterprise sources with scalable BI reporting environments.',tags:['ADF','Databricks','Synapse','Snowflake','Power BI'],type:'pipeline'}
];

export const personalProjects = [
 {title:'Supply Chain & Logistics Dashboard',category:'SUPPLY CHAIN ANALYTICS',description:'An executive view of a Samsung-themed supply chain: supplier lead times, product stock, shipments and customer revenue, with revenue, profit and order-performance KPIs in one place.',tags:['Executive Reporting','Inventory','Logistics'],image:'/projects/supply-chain.png',alt:'Supply chain dashboard showing supplier lead times, inventory, shipment costs and customer revenue.',width:1414,height:788},
 {title:'Uber Ride & Revenue Analytics',category:'MOBILITY ANALYTICS',description:'A ride-hailing dashboard exploring completed and lost bookings, monthly revenue, vehicle performance and trip distance, alongside pickup locations and customer and driver ratings.',tags:['Power BI','Ride Performance','Revenue'],image:'/projects/ride-analytics.png',alt:'Uber-themed dashboard showing bookings, monthly revenue, vehicle types, locations and rider ratings.',width:1517,height:842},
 {title:'Personal Finance Dashboard',category:'FINANCIAL ANALYTICS',description:'A view of income, expenses and savings over time. Compare spending categories, track savings allocations and explore year-based financial trends through a focused dashboard.',tags:['Power BI','Expense Analysis','Savings'],image:'/projects/finance.png',alt:'Finance dashboard with expense trends, income and savings KPIs, spending breakdowns and a financial summary.',width:1483,height:843}
];
